version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./Admin/frontend
    ports:
      - "5041:3000"  # Expose the frontend port
    volumes:
      - ./Admin/frontend:/app/frontend  # Mount the frontend directory

  backend:
    container_name: backend
    build:  ./Admin/Backend
    volumes:
      - ./Admin/Backend:/app/backend  # Mount the backend directory

  kiosk:
    container_name: kiosk
    build: ./Kiosk
    ports:
      - "8000:8000"  # Expose the kiosk port
    volumes:
      - ./Kiosk:/app/Kiosk  # Mount the kiosk directory

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ai;
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_test:/var/lib/ai


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpMyAdmin
    restart: always
    ports:
      - "8080:80"  # Expose phpMyAdmin on port 8080
    environment:
      PMA_HOST: db              
      PMA_PORT: 3306
      PMA_USER: root
    depends_on:
      - db

volumes:
  mysql_data_test:
    driver: local