FROM nginx
COPY dist /usr/share/nginx/html


# FROM node:16.13.1 as build-stage

# # Set working directory
# WORKDIR /app

# # Copy package files
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# COPY . .

# # Build application
# RUN npm run build

# # Production stage
# FROM nginx:alpine

# # Copy build files to Nginx
# COPY --from=build-stage /app/dist /usr/share/nginx/html

# EXPOSE 80

# # Start Nginx
# CMD ["nginx", "-g", "daemon off;"]



